# Nama workflow
name: Clean and Normalize Data

on:
  #setiap kali ada 'push' ke branch manapun
  push:
  
  #menjalankan workflow ini secara manual
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Run Preprocessing and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori Anda
      - name: Check out repository
        uses: actions/checkout@v4

      # --- LANGKAH DEBUGGING 1 ---
      # Tampilkan semua file yang ada di repositori
      - name: 1.5 - List files after checkout
        run: |
          echo "Melihat file di root direktori:"
          ls -l

      # Langkah 2: Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Langkah 3: Install library yang dibutuhkan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      # Langkah 4: Jalankan skrip Python Anda
      - name: Run automate_Andreas-Kevin script
        run: python automate_Andreas-Kevin.py

      - name: 4.5 - List files after python script
        run: |
          echo "Melihat file setelah skrip Python dijalankan:"
          ls -l

      # Langkah 5: Upload hasil sebagai Artifact
      - name: Upload processing artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processing-results
          path: |
            diabetes_cleaned.csv
            minmax_scaler.joblib
          retention-days: 7

