# Nama workflow
name: Clean and Normalize Data

on:
  #setiap kali ada 'push' ke branch manapun
  push:
  
  #menjalankan workflow ini secara manual
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Run Preprocessing and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori Anda
      - name: Check out repository
        uses: actions/checkout@v4

      # Langkah 2: Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Langkah 3: Install library yang dibutuhkan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      # Langkah 4: Jalankan skrip Python Anda
      - name: Run preprocessing script
        run: python preprocess.py

      # Langkah 5: (BARU) Upload hasil 'diabetes_cleaned.csv' sebagai Artifact
      - name: Upload cleaned data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleaned-diabetes-data
          path: diabetes_cleaned.csv
          retention-days: 7