# Nama Workflow yang akan muncul di tab Actions
name: 1. Preprocessing Data

on:
  push:
    branches:
      - main
      
  # Memperbolehkan trigger manual dari tab Actions di GitHub
  workflow_dispatch:

jobs:
  build-and-process-data:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout (Unduh) kode repository
        uses: actions/checkout@v4

      - name: 2. Siapkan lingkungan Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: 3. Install dependencies (library yang dibutuhkan)
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn numpy

      - name: 4. Jalankan script preprocessing
        run: python automate_Andreas-Kevin.py

      - name: 5. Upload hasil preprocessing sebagai artifact
        uses: actions/upload-artifact@v4
        with:
          # Nama file zip yang akan dihasilkan
          name: Andreaskevin_preprocessing
          path: |
            train_set.csv
            test_set.csv

